---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# POST credentialgroup     Create a credential group
# Method                   POST
# Requires Authentication? Yes
# 
# Input type               Credential Group
# Result type              Guid

# TODO: test

# Check for required keys
- assert:
    that:
      - "['Name', 'ParentId'] is subset(pps_credentialgroup.keys())"
    msg: "'Name', and/or 'ParentId' key(s) NOT in pps_credentialgroup: {{ pps_credentialgroup }}"
  no_log: false

- assert:
    that:
      - "pps_credentialgroup.ParentId is match(match_pps_credentialgroupgroup_id)"
    msg: "Invalid ID! pps_credentialgroup.ParentId: {{ pps_credentialgroup.ParentId }}"
  no_log: false

- set_fact:
    uri_request_body:
      Id:       "00000000-0000-0000-0000-00000000000" # *
      # This will be an Empty Guid when creating a new CredentialGroup.
      Name:     "{{ pps_credentialgroup.Name }}" # *
      ParentId: "{{ pps_credentialgroup.ParentId }}" # *
      Notes:    "{{ pps_credentialgroup.Notes | default(None) }}" # **
      #~ Created:  "{{ pps_credentialgroup.Created }}" # **
      #~ Modified: "{{ pps_credentialgroup.Modified }}" # **
      #~ Expires:  "{{ pps_credentialgroup.Expires | default(None) }}" # **
      CustomUserFields:        "{{ pps_credentialgroup.CustomUserFields | default({}) }}" # **
      CustomApplicationFields: "{{ pps_credentialgroup.CustomApplicationFields | default({}) }}" # **
      Attachments:             "{{ pps_credentialgroup.Attachments | default([]) }}" # **
      Tags:                    "{{ pps_credentialgroup.Tags | default([]) }}" # **
      UsageComment:            "{{ pps_credentialgroup.UsageComment | default(None) }}" # **

# * required field for creating a Folder
# ** omitting this field will give it a null or default value

- name: Create a credential group
  uri:
    url: "{{ pps_rest_api_url }}/credentialgroup"
    method: POST
    #validate_certs: no
    return_content: yes
    body: '{{ uri_request_body | to_json }}'
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

- set_fact:
    pps_create_credentialgroup_result: "{{ uri_result.json }}"
