---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# DELETE credentialgroup/:id Delete a credential group.
# Method                     DELETE
# Requires Authentication?   Yes
# 
# Parameters
# id                         GUID for credential group
# 
# Result type                None

# TODO: test

# Check for required keys
- assert:
    that:
      - "['Id'] is subset(pps_credentialgroup.keys())"
    msg: "'Id' key NOT in pps_credentialgroup: {{ pps_credentialgroup }}"
  no_log: false

- assert:
    that:
      - "pps_credentialgroup.Id is match(match_pps_credentialgroup.Id)"
    msg: "Invalid ID! pps_credentialgroup.Id: {{ pps_credentialgroup.Id }}"
  no_log: false

- name: Delete a credential group
  uri:
    url: "{{ pps_rest_api_url }}/credentialgroup/{{ pps_credentialgroup.Id }}"
    method: DELETE
    #validate_certs: no
    return_content: yes
    status_code: 204
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

- set_fact:
    pps_delete_credentialgroup_result: !!null
