---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# DELETE credential/:id    Delete a credential.
# Method                   DELETE
# Requires Authentication? Yes
#
# Parameters   
#   id                     GUID for credential
#
# Result type              None

# Check for required keys
- assert:
    that:
      - "['Id'] is subset(pps_credential.keys())"
    msg: "'Id' key NOT in pps_credential: {{ pps_credential }}"
  no_log: false

- assert:
    that:
      - "pps_credential.Id is match(match_pps_credential_id)"
    msg: "Invalid ID! pps_credential.Id: {{ pps_credential.Id }}"
  no_log: false

- name: Delete a credential
  uri:
    url: "{{ pps_rest_api_url }}/credential/{{ pps_credential.Id }}"
    method: DELETE
    #validate_certs: no
    return_content: yes
    status_code: 204
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

- set_fact:
    pps_delete_credential_result: !!null
