---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# GET credentialgroup/root Read the root credential group.
# Method                   GET
# Requires Authentication? Yes
#
# Result type              Credential Group

- name: Read the root credential group
  uri:
    url: "{{ pps_rest_api_url }}/credentialgroup/root"
    method: GET
    #validate_certs: no
    return_content: yes
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

# "uri_result": {
#     "cache_control": "no-cache, no-store, must-revalidate",
#     "changed": false,
#     "connection": "close",
#     "content": "\"2f52c215-a8c0-4347-9e74-b630bd834845\"",
#     "content_length": "38",
#     "content_type": "application/json; charset=utf-8",
#     "cookies": {},
#     "date": "Sat, 30 Mar 2019 10:08:07 GMT",
#     "expires": "-1",
#     "failed": false,
#     "json": "2f52c215-a8c0-4347-9e74-b630bd834845",
#     "msg": "OK (38 bytes)",
#     "pragma": "no-cache",
#     "redirected": false,
#     "server": "[OBFUSCATED]",
#     "status": 200,
#     "url": "https://localhost:10001/api/v4/rest/credentialgroup/root",
#     "x_aspnet_version": "[OBFUSCATED]",
#     "x_content_type_options": "nosniff",
#     "x_powered_by": "ASP.NET",
#     "x_ua_compatible": "IE=Edge",
#     "x_xss_protection": "1"
# }

- set_fact:
    pps_read_credentialgroup_root_result: "{{ uri_result.json }}"
