---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# GET credentialgroup/:id  Read a credential group.
# Method                   GET
# Requires Authentication? Yes
# 
# Parameters
# id                       Optional. GUID for credential group.
#                          If passed in, direct descendents will be included in the result.
#                          If not passed in, the entire password hierarchy will be returned.
# 
# Result type              Credential Group

# Check for required keys
# None

- assert:
    that:
      - "pps_credentialgroup.Id is match(match_pps_credentialgroup.Id)"
    msg: "Invalid ID! pps_credentialgroup.Id: {{ pps_credentialgroup.Id }}"
  when: pps_credentialgroup is defined and 'Id' in pps_credentialgroup
  no_log: false

- set_fact:
    pps_credentialgroup: {Id: ""}
  when: (pps_credentialgroup is not defined) or
        (pps_credentialgroup is defined and 'Id' not in pps_credentialgroup)

- name: Read a credential group
  uri:
    url: "{{ pps_rest_api_url }}/credentialgroup/{{ pps_credentialgroup.Id }}"
    method: GET
    #validate_certs: no
    return_content: yes
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

# "uri_result.json": {
#     "Attachments": [], 
#     "Children": [], 
#     "CommentPrompts": {
#         "AskForCommentOnModifyEntries": false, 
#         "AskForCommentOnModifyFolders": false, 
#         "AskForCommentOnMoveEntries": false, 
#         "AskForCommentOnMoveFolders": false, 
#         "AskForCommentOnViewOffline": false, 
#         "AskForCommentOnViewPassword": false
#     }, 
#     "Created": "2019-03-29T09:29:59+13:00", 
#     "Credentials": [
#         {
#             "Attachments": [], 
#             "CommentPrompts": {
#                 "AskForCommentOnModifyEntries": false, 
#                 "AskForCommentOnModifyFolders": false, 
#                 "AskForCommentOnMoveEntries": false, 
#                 "AskForCommentOnMoveFolders": false, 
#                 "AskForCommentOnViewOffline": false, 
#                 "AskForCommentOnViewPassword": false
#             }, 
#             "Created": "2019-03-29T09:29:59+13:00", 
#             "CustomApplicationFields": {}, 
#             "CustomUserFields": {}, 
#             "Expires": null, 
#             "GroupId": "6aaa4688-64cb-48cc-ad41-087789d18292", 
#             "HasModifyEntriesAccess": true, 
#             "HasViewEntryContentsAccess": true, 
#             "Id": "84703ad8-a96b-4ed4-b62e-e7f8d80ac6bc", 
#             "Modified": "2019-03-29T09:29:59+13:00", 
#             "Name": "foo.example.com", 
#             "Notes": "", 
#             "Password": null, 
#             "Tags": [], 
#             "Url": "", 
#             "UsageComment": null, 
#             "Username": "username"
#         }, 
#         {
#             "Attachments": [
#                 {
#                     "AttachmentId": "00000000-0000-0000-0000-000000000000", 
#                     "CredentialObjectId": "cdd618cd-6c83-4005-8517-a75d72a9a9a9", 
#                     "FileData": "jjyBHCYlP...7Dn0fhDwa1m63RcqojeSGb5pm+BI2deBUEwvRwqxTY=", 
#                     "FileName": "bar.example.com.cer", 
#                     "FileSize": 0
#                 }, 
#                 {
#                     "AttachmentId": "00000000-0000-0000-0000-000000000000", 
#                     "CredentialObjectId": "cdd618cd-6c83-4005-8517-a75d72a9a9a9", 
#                     "FileData": "Wjv...9uUahIzTcchy6NOUYt8+AzMiAPPRQObTBurPE+wuYGGRI4g==", 
#                     "FileName": "bar.example.com.key", 
#                     "FileSize": 0
#                 } 
#             ], 
#             "CommentPrompts": {
#                 "AskForCommentOnModifyEntries": false, 
#                 "AskForCommentOnModifyFolders": false, 
#                 "AskForCommentOnMoveEntries": false, 
#                 "AskForCommentOnMoveFolders": false, 
#                 "AskForCommentOnViewOffline": false, 
#                 "AskForCommentOnViewPassword": false
#             }, 
#             "Created": "2019-03-29T09:29:59+13:00", 
#             "CustomApplicationFields": {}, 
#             "CustomUserFields": {}, 
#             "Expires": null, 
#             "GroupId": "6aaa4688-64cb-48cc-ad41-087789d18292", 
#             "HasModifyEntriesAccess": true, 
#             "HasViewEntryContentsAccess": true, 
#             "Id": "cdd618cd-6c83-4005-8517-a75d72a9a9a9", 
#             "Modified": "2019-03-29T09:29:59+13:00", 
#             "Name": "bar.example.com", 
#             "Notes": "", 
#             "Password": null, 
#             "Tags": [
#                 {
#                     "Name": "test"
#                 }
#             ], 
#             "Url": "", 
#             "UsageComment": null, 
#             "Username": ""
#         }
#     ], 
#     "CustomApplicationFields": {}, 
#     "CustomUserFields": {}, 
#     "Expires": null, 
#     "HasModifyEntriesAccess": true, 
#     "HasViewEntryContentsAccess": true, 
#     "Id": "6aaa4688-64cb-48cc-ad41-087789d18292", 
#     "Modified": "2019-03-29T09:29:59+13:00", 
#     "Name": "Folder", 
#     "Notes": null, 
#     "ParentId": "cd246773-0829-48b6-ba00-f82f4d7598ec", 
#     "Tags": [], 
#     "UsageComment": null
# }

- set_fact:
    pps_read_credentialgroup_results: "{{ uri_result.json }}"
