---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# PUT credential/:id       Update a credential.
# Method                   PUT
# Requires Authentication? Yes
#
# Parameters   
#   id                     GUID for credential
#
# Input type               Credential
# Result type              None

# Check for required keys
- assert:
    that:
      - "['Name', 'Password', 'GroupId', 'Id'] is subset(pps_credential.keys())"
    msg: "'Name', 'Password', 'GroupId', and/or 'Id' key(s) NOT in pps_credential: {{ pps_credential }}"
  no_log: false

- assert:
    that:
      - "pps_credential.Id is match(match_pps_credential_id)"
    msg: "Invalid ID! pps_credential.Id: {{ pps_credential.Id }}"
  no_log: false

- assert:
    that:
      - "pps_credential.GroupId is match(match_pps_credentialgroup_id)"
    msg: "Invalid ID! pps_credential.GroupId: {{ pps_credential.GroupId }}"
  no_log: false

- set_fact:
    uri_request_body:
      Id:       "{{ pps_credential.Id }}" # *
      Name:     "{{ pps_credential.Name }}" # *
      Password: "{{ pps_credential.Password }}" # *
      Username: "{{ pps_credential.Username | default('') }}" # **
      Url:      "{{ pps_credential.Url | default('') }}" # **
      Notes:    "{{ pps_credential.Notes | default('') }}" # **
      GroupId:  "{{ pps_credential.GroupId }}" # *
      #~ Created:  "{{ pps_credential.Created }}" # * [not really]
      #~ Modified: "{{ pps_credential.Modified }}" # * [not really]
      #~ Expires:  "{{ pps_credential.Expires | default(None) }}" # **
      CustomUserFields:        "{{ pps_credential.CustomUserFields | default({}) }}" # **
      CustomApplicationFields: "{{ pps_credential.CustomApplicationFields | default({}) }}" # **
      Attachments:             "{{ pps_credential.Attachments | default([]) }}" # **
      UsageComment:            "{{ pps_credential.UsageComment | default(None) }}" # **
      Tags:                    "{{ pps_credential.Tags | default([]) }}" # **

# * required field for updating an Entry
# ** omitting this field will give it a null or default value

- name: Update a credential
  uri:
    url: "{{ pps_rest_api_url }}/credential/{{ pps_credential.Id }}"
    method: PUT
    #validate_certs: no
    return_content: yes
    body: '{{ uri_request_body | to_json }}'
    status_code: 204
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

# "uri_result": {
#     "cache_control": "no-cache, no-store, must-revalidate",
#     "changed": false,
#     "connection": "close",
#     "content": "",
#     "cookies": {},
#     "date": "Sat, 30 Mar 2019 10:08:07 GMT",
#     "expires": "-1",
#     "failed": false,
#     "msg": "OK (unknown bytes)",
#     "pragma": "no-cache",
#     "redirected": false,
#     "server": "[OBFUSCATED]",
#     "status": 204,
#     "url": "https://localhost:10001/api/v4/rest/credential/ba2f8a0f-d49b-4f18-8d11-1be03d347411",
#     "x_aspnet_version": "[OBFUSCATED]",
#     "x_content_type_options": "nosniff",
#     "x_powered_by": "ASP.NET",
#     "x_ua_compatible": "IE=Edge",
#     "x_xss_protection": "1"
# }

- set_fact:
    pps_update_credential_result: !!null
