---
# https://info.pleasantsolutions.com/Documentation/Pleasant_Password_Server/
#  M._Programmatic_Access/_Password_Server_REST_API_Documentation/Service_Models
#
# PUT credentialgroup/:id  Update a credential group
# Method                   PUT
# Requires Authentication? Yes
# 
# Parameters
# id                       GUID for credential group
# 
# Input type               Credential Group
# Result type              None

# TODO: test

# Check for required keys
- assert:
    that:
      - "['Name', 'ParentId', 'Id'] is subset(pps_credentialgroup.keys())"
    msg: "'Name', 'ParentId', and/or 'Id' key(s) NOT in pps_credentialgroup: {{ pps_credentialgroup }}"
  no_log: false

- assert:
    that:
      - "pps_credentialgroup.ParentId is match(match_pps_credentialgroupgroup_id)"
    msg: "Invalid ID! pps_credentialgroup.ParentId: {{ pps_credentialgroup.ParentId }}"
  no_log: false

- assert:
    that:
      - "pps_credentialgroup.Id is match(match_pps_credentialgroupgroup_id)"
    msg: "Invalid ID! pps_credentialgroup.Id: {{ pps_credentialgroup.Id }}"
  no_log: false

- set_fact:
    uri_request_body:
      Id:       "{{ pps_credentialgroup.Id }}" # *
      # This will be an Empty Guid when creating a new CredentialGroup.
      Name:     "{{ pps_credentialgroup.Name }}" # *
      ParentId: "{{ pps_credentialgroup.ParentId }}" # *
      Notes:    "{{ pps_credentialgroup.Notes | default(None) }}" # **
      #~ Created:  "{{ pps_credentialgroup.Created }}" # **
      #~ Modified: "{{ pps_credentialgroup.Modified }}" # **
      #~ Expires:  "{{ pps_credentialgroup.Expires | default(None) }}" # **
      CustomUserFields:        "{{ pps_credentialgroup.CustomUserFields | default({}) }}" # **
      CustomApplicationFields: "{{ pps_credentialgroup.CustomApplicationFields | default({}) }}" # **
      Attachments:             "{{ pps_credentialgroup.Attachments | default([]) }}" # **
      Tags:                    "{{ pps_credentialgroup.Tags | default([]) }}" # **
      UsageComment:            "{{ pps_credentialgroup.UsageComment | default(None) }}" # **

# * required field for updating a Folder
# ** omitting this field will give it a null or default value

- name: Update a credential group
  uri:
    url: "{{ pps_rest_api_url }}/credentialgroup/{{ pps_credentialgroup.Id }}"
    method: PUT
    #validate_certs: no
    return_content: yes
    status_code: 204
    body: '{{ uri_request_body | to_json }}'
    headers:
      Authorization: "{{ pps_oauth2_token.token_type }} {{ pps_oauth2_token.access_token }}"
      Content-Type: "application/json"
      Cache-Control: "no-cache"
  register: uri_result
  delegate_to: localhost

- set_fact:
    pps_update_credentialgroup_result: !!null
